# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(568, 333)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 0, 531, 311))
        self.tabWidget.setObjectName("tabWidget")
        self.tab_1 = QtWidgets.QWidget()
        self.tab_1.setObjectName("tab_1")
        self.add_tab_1_button = QtWidgets.QPushButton(self.tab_1)
        self.add_tab_1_button.setGeometry(QtCore.QRect(0, 0, 113, 32))
        self.add_tab_1_button.setObjectName("add_tab_1_button")
        self.tab_1_table = QtWidgets.QTableWidget(self.tab_1)
        self.tab_1_table.setGeometry(QtCore.QRect(0, 30, 1180, 230))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tab_1_table.setFont(font)
        self.tab_1_table.setAutoScrollMargin(16)
        self.tab_1_table.setAlternatingRowColors(True)
        self.tab_1_table.setColumnCount(5)
        self.tab_1_table.setObjectName("tab_1_table")
        self.tab_1_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tab_1_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tab_1_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tab_1_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tab_1_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tab_1_table.setHorizontalHeaderItem(4, item)
        self.tab_1_table.horizontalHeader().setCascadingSectionResizes(False)
        self.tab_1_table.horizontalHeader().setDefaultSectionSize(100)
        self.tab_1_table.horizontalHeader().setStretchLastSection(False)
        self.tab_1_table.verticalHeader().setVisible(False)
        self.tab_1_table.verticalHeader().setHighlightSections(True)
        self.pushButton = QtWidgets.QPushButton(self.tab_1)
        self.pushButton.setGeometry(QtCore.QRect(220, 0, 113, 32))
        self.pushButton.setObjectName("pushButton")
        self.tabWidget.addTab(self.tab_1, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tab_2_table = QtWidgets.QTableWidget(self.tab_2)
        self.tab_2_table.setGeometry(QtCore.QRect(0, 30, 1180, 230))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tab_2_table.setFont(font)
        self.tab_2_table.setAlternatingRowColors(True)
        self.tab_2_table.setColumnCount(5)
        self.tab_2_table.setObjectName("tab_2_table")
        self.tab_2_table.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.tab_2_table.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tab_2_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tab_2_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tab_2_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tab_2_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tab_2_table.setHorizontalHeaderItem(4, item)
        self.tab_2_table.horizontalHeader().setDefaultSectionSize(100)
        self.tab_2_table.verticalHeader().setVisible(False)
        self.add_tab_2_button = QtWidgets.QPushButton(self.tab_2)
        self.add_tab_2_button.setGeometry(QtCore.QRect(0, 0, 113, 32))
        self.add_tab_2_button.setObjectName("add_tab_2_button")
        self.tabWidget.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 568, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionNew = QtWidgets.QAction(MainWindow)
        self.actionNew.setObjectName("actionNew")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionExport_Recipe = QtWidgets.QAction(MainWindow)
        self.actionExport_Recipe.setObjectName("actionExport_Recipe")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionExport_Recipe)
        self.menuFile.addAction(self.actionExit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Calculator"))
        self.add_tab_1_button.setText(_translate("MainWindow", "Add Row"))
        item = self.tab_1_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Col1"))
        item = self.tab_1_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Col2"))
        item = self.tab_1_table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Col3"))
        item = self.tab_1_table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Col4"))
        item = self.tab_1_table.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Col5"))
        self.pushButton.setText(_translate("MainWindow", "PushButton"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_1), _translate("MainWindow", "Tab1"))
        item = self.tab_2_table.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tab_2_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Col1"))
        item = self.tab_2_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Col2"))
        item = self.tab_2_table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Col3"))
        item = self.tab_2_table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Col4"))
        item = self.tab_2_table.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Col5"))
        self.add_tab_2_button.setText(_translate("MainWindow", "Add Row"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Tab2"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionNew.setText(_translate("MainWindow", "New..."))
        self.actionOpen.setText(_translate("MainWindow", "Import Recipe..."))
        self.actionExport_Recipe.setText(_translate("MainWindow", "Export Recipe..."))
        self.actionExit.setText(_translate("MainWindow", "Close"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
